### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hanjianwei** [hanjianwei/ros#1]
- [ ] Bridge setup
- [ ] MetaRouter setup
- [ ] [dnsmasq](https://cokebar.info/archives/1410)
    - [ ] [dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list)
    - [ ] [gfwlist2dnsmasq](https://github.com/cokebar/gfwlist2dnsmasq)
- [ ] VPN setup
